### ISSUE TITLE
Direction des joueurs

### ISSUE THREAD

**Issue by rpellerin** [snakeworld/snakeworld#2]
A quoi correspond {snakes: [{**direction: 'x'**, ...}, ...], ...} ? La direction que va prendre chaque snake au prochain tour ?
Cela permettrait donc de savoir où sera la tête de chaque serpent le tour d'après (150ms plus tard) ?

**Comment by trecouvr** [comment]
Ça correspond à la direction du serpent lors du dernier tour. Au prochain tour il peut décider de la changer tu ne peut donc pas prédit de manière exacte où sera la tête du serpent au prochain tour mais ça donne quand même une bonne indication.

**Comment by rpellerin** [comment]
Merci !
