### ISSUE TITLE
2 serpents vont sur la même case

### ISSUE THREAD

**Issue by rpellerin** [snakeworld/snakeworld#3]
Bonjour

Si la tête d'un serpent est en 0,0, et celle d'un autre en 1,1, si les deux demandent à aller en 0,1, que se passe-t-il ? Qui tue qui ?
Et s'il y a un fruit ? Qui le mange ?

Merci

**Comment by trecouvr** [comment]
Hello,

Si deux serpent vont sur la même case au même tour les deux meurent. Si il y a un fruit, un des deux au hasard le mange et augmente son score de 1 juste avant de mourir :p 

Parties du code en rapport avec ça :
https://github.com/snakeworld/snakeworld/blob/master/snakeworld/server.py#L69
https://github.com/snakeworld/snakeworld/blob/master/snakeworld/server.py#L120

**Comment by rpellerin** [comment]
Merci !
